version: '3.1'

services:

  terraform:
    image: hashicorp/terraform:1.1.2
    volumes:
      - $PWD/infrastructure:/infrastructure
      - $HOME/.aws:/root/.aws
    working_dir: /infrastructure
    environment:
      - TF_VAR_vpc_id
      - TF_VAR_postgresql_password
      - TF_VAR_domain_name
      - TF_VAR_certificate_arn
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
